### ISSUE TITLE
Geometry optimization fails 

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#140]
After the most recent merge, the OPTIMIZE keyword is not properly read. The following fails: 

```
 @ Read Job And Atom

  KEYWORD=DFT LIBXC=HYB_GGA_XC_PBEH BASIS=DEF2-SVP CUTOFF=1.0E-9 DENSERMS=1.0E-6 OPTIMIZE DIPOLE CHARGE=+1                                                                                             

| ERROR: Error with keyword OPTIMIZE encountered.

| Error Termination. Task Failed on: Tue Mar  9 21:51:27 2021
```

But this one doesn't fail. 

```
@ Read Job And Atom

  KEYWORD=HF BASIS=6-31G CUTOFF=1.0E-9 DENSERMS=1.0E-6  ZMAKE OPTIMIZE=5 DIPOLE                                                                                                                        
 ============== JOB CARD =============
 METHOD = HATREE FOCK
 DIRECT SCF
 SAD INITAL GUESS
 USE DIIS SCF
 PRINT ENERGY EVERY CYCLE
 Z-MATRIX CONSTRUCTION
 DIPOLE
 GEOMETRY OPTIMIZATION NUMERICAL GRADIENT
 REQUEST CRITERIA FOR GEOMETRY CONVERGENCE:
      MAX ALLOWED GEO CHANGE  =  0.189E+00
      MAX GEOMETRY CHANGE     =  0.180E-02
      GEOMETRY CHANGE RMS     =  0.120E-02
      MAX GRADIENT CHANGE     =  0.100E-02
      GRADIENT NORMALIZATION  =  0.300E-03
 GRADIENT CALCULATION
 MAX SCF CYCLES =    200
 MAX DIIS CYCLES =   10
 DELTA DENSITY START CYCLE = 1000
 COMPUTATIONAL CUTOFF:
      TWO-e INTEGRAL   =  0.100E-08
      BASIS SET PRIME  =  0.100E-19
      MATRIX ELEMENTS  =  0.100E-09
      BASIS FUNCTION   =  0.100E-09
      GRADIENT CUTOFF  =  0.100E-08
 DENSITY MATRIX MAXIMUM RMS FOR CONVERGENCE  =  0.100E-05
 BASIS SET = 6-31G,  TYPE = CARTESIAN
| BASIS FILE = /home/mmanathunga/fix109/basis/6-31G.BAS

 @ Finish reading job


 @ Begin SAD initial guess

 For Atom Kind =    1
 ELEMENT = O
 BASIS FUNCTIONS =    9
 For Atom Kind =    2
 ELEMENT = H
 BASIS FUNCTIONS =    2

 @ Finish SAD initial guess

```

**Comment by Madu86** [comment]
@Altaimorin The only difference between the two OPTIMIZE keywords is that the latter have `=5`  Please fix this ASAP. QUICK must be able to read OPTIMIZE keyword without a user specified maximum number of optimization cycles.

**Comment by agoetz** [comment]
Good catch - this needs to be fixed asap. Perhaps the best would be to have an additional optional argument to the parser functions that defaults to .true. and can be used as
```
! This keyword can be present but does not require an associated value
call read(line, keyword, value, required=.false.)
```
and then only throw an error if an equal sign is found after the keyword but reading a value fails.

This will require more advanced parsing, because then you need to know how to inform a user that he should not use a space after OPTIMIZE, e.g. "optimize =25".

Instead of requiring that no space is used, it might be better to actually allow blanks (including space and tab characters) and you just scan for the next non-blank character. If it is an equal sign, then you have an assignment, and you scan again to find the value field which must terminate with a blank space.
