### ISSUE TITLE
QUICK with CUDA 11.4

### ISSUE THREAD

**Issue by mboisson** [merzlab/QUICK#218]
Hi,
We have CUDA 11.4 installed, and I'm trying to build AmberTools, with QUICK. The CMake recipe constraints to CUDA <= 11.2. Why is that ? Why not just let CUDA unconstrained and ask the builder to select which compute capabilitie(s) to build for ?

**Comment by Madu86** [comment]
Hi @mboisson,

Unfortunately this is something coming from Amber build system. It compiles cuda source files for all possible architectures that a given toolkit supports. I think it is limited to <=11.2 just because nobody has tested with toolkits above that. Feel free to change and try to compile the code.
In standalone QUICK CMake build system, you can specify an architecture with QUICK_USER_ARCH flag.

**Comment by mboisson** [comment]
I would rather be able to specify a list of architectures directly, we routinely build lots of CUDA applications for multiple architectures, listed in our config, which we adjust based on the most recent toolkit: 
https://github.com/ComputeCanada/easybuild-computecanada-config/blob/main/config-gentoo.cfg#L4

**Comment by mboisson** [comment]
I patched the CudaConfig.cmake file before installing it.
