### ISSUE TITLE
Platinum detected as phosphorus

### ISSUE THREAD

**Issue by thosoo** [merzlab/QUICK#356]
I tried to make an optimization of a platinum complex with f functions enabled and a modified def2-tzvp basis set to contain values for all elements. However, when starting the optimization, QUICK complains about unpaired electrons and that it requires UHF/UDFT calculations. Changing platinum to palladium in the input file made the calculation run fine again.

```
 ============== JOB CARD =============
 METHOD = DENSITY FUNCTIONAL THEORY
 DENSITY FUNCTIONAL = B3LYP
 DIRECT SCF
 SAD INITAL GUESS
 USE DIIS SCF
 PRINT ENERGY EVERY CYCLE
 READ SAD GUESS FROM FILE
 STANDARD GRID = SG1
 GEOMETRY OPTIMIZATION ANALYTICAL GRADIENT
 REQUEST CRITERIA FOR GEOMETRY CONVERGENCE:
      MAX ALLOWED GEO CHANGE  =  0.189E+00
      MAX GEOMETRY CHANGE     =  0.180E-02
      GEOMETRY CHANGE RMS     =  0.120E-02
      MAX GRADIENT CHANGE     =  0.100E-02
      GRADIENT NORMALIZATION  =  0.300E-03
      MAX OPTIMIZATION CYCLE  =     0
 GRADIENT CALCULATION
 MAX SCF CYCLES =   1000
 MAX DIIS CYCLES =   10
 DELTA DENSITY START CYCLE =    3
 COMPUTATIONAL CUTOFF:
      TWO-e INTEGRAL   =  0.100E-09
      BASIS SET PRIME  =  0.100E-10
      MATRIX ELEMENTS  =  0.100E-09
      BASIS FUNCTION   =  0.100E-05
      GRADIENT CUTOFF  =  0.100E-06
 DENSITY MATRIX MAXIMUM RMS FOR CONVERGENCE  =  0.100E-05
 BASIS SET = DEF2-TZVP,  TYPE = CARTESIAN
| BASIS FILE = /usr/local/basis/DEF2-TZVP.BAS

 @ Finish reading job


 @ Begin SAD initial guess

 For Atom Kind =    1
 ELEMENT = N
 BASIS FUNCTIONS =   36
 For Atom Kind =    2
 ELEMENT = C
 BASIS FUNCTIONS =   36
 For Atom Kind =    3
 ELEMENT = H
 BASIS FUNCTIONS =    6
 For Atom Kind =    4
 ELEMENT = P
 BASIS FUNCTIONS =   42

 @ Finish SAD initial guess


 @ Begin Reading Molecular Information


| Error: Systems with unpaired electrons require UHF/UDFT calculations.

| Error Termination. Task Failed on: Mon Mar 25 08:48:02 2024
```

**Comment by agoetz** [comment]
Atom types of heavy elements beyond Hf are not identified correctly due to a bug. I am issuing a fix with a PR that will close this issue. 

However, even if molecular coordinates with Pt are read correctly, I do not recommend performing all-electron calculations on elements heavier than Kr without effective core potentials (ECPs). Relativistic effects become important for these heavy elements. This is why basis sets for non-relativistic calculations of elements heavier than Kr use ECPs. ECPs are not yet implemented in QUICK.

Please be also aware that we have not performed many tests on first row transition metals (Fe to Zn). Feedback is always appreciated.
