### ISSUE TITLE
./runtest after compile finish

### ISSUE THREAD

**Issue by Vincent-2019** [merzlab/QUICK#374]
I got this error in ./runtest --full 
plz help me,Thx!
![image](https://github.com/user-attachments/assets/f5b73ff6-6bc8-4dc5-be66-bc3a209914e4)
It passed rhf but cant passed BLYP,B3LYP,DFT.
with error(Error: quick.cuda.MPI execution failed.)
I already check my environment variable,and still have problem
Detail:
CUDA version:12.4
GCC version :12.3
OpenMPI:5.0.0

#GCC
export PATH=/home/vincent/Downloads/gcc-12.3.0/bin:$PATH

#OpenMPI
export PATH=/home/vincent/Downloads/openmpi-5.0.0/bin:$PATH
export LD_LIBRARY_PATH=/home/vincent/lib64/openmpi-5.0.0/lib64:$LD_LIBRARY_PATH

#CUDA
export PATH=/usr/local/cuda-12.4/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-12.4/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda-12.4

#export PATH=/usr/local/cuda-10.0/bin:$PATH
#export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH

#G16 environment
export g16root=/usr/local
export GAUSS_SCRDIR=/tmp/g16tmp
source $g16root/g16/bsd/g16.profile

#EXPO2014
export PATH=/home/vincent/bin/expo/bin:$PATH

source .cry23.bashrc
##

**Comment by agoetz** [comment]
Please run the serial, mpi, cuda and cudampi tests separately. (see `./runtest --help` for options).

Does the single GPU CUDA version pass the tests? (`./runtest --full --cuda`)

How many and what type of GPUs do you have in your system and what MPI command are you using (e.g. `export DO_PARALLEL='mpirun -np 2'`)?
I am asking because the code will run out of memory on most GPUs if you try to launch more than one task per GPU (in terms of performance that also would not make sense).

**Comment by agoetz** [comment]
I am closing this issue since I have not heard back. If you have new information, please re-open the issue.
