### ISSUE TITLE
MPI run fails

### ISSUE THREAD

**Issue by merzlab** [merzlab/QUICK#47]
I am experiencing the following segfault for taxol B3LYP/6-31G** gradient calculation. 

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
quick.MPI          0000000000B2351D  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F014B0A0630  Unknown               Unknown  Unknown
quick.MPI          00000000004CAF23  Unknown               Unknown  Unknown
quick.MPI          00000000004C96CC  Unknown               Unknown  Unknown
quick.MPI          000000000041FC29  Unknown               Unknown  Unknown
quick.MPI          0000000000423603  Unknown               Unknown  Unknown
quick.MPI          0000000000405121  Unknown               Unknown  Unknown
quick.MPI          0000000000404F5E  Unknown               Unknown  Unknown
libc-2.17.so       00007F014A9E3555  __libc_start_main     Unknown  Unknown
quick.MPI          0000000000404E69  Unknown               Unknown  Unknown

QUICK version: v21.03, mpi executable
MPI command: mpirun -np 4
Compiler: Intel/2018.0.5, MPI: intelmpi/2018.0.5
System: Centos 7, 3.10.0-1127.18.2.el7.x86_64
CPU: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
Memory: 64 GB

**Comment by Madu86** [comment]
This issue is caused by intrinsic matrix multiplication in diss. 

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
quick.MPI          0000000000F0013D  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FEF0AFB5630  Unknown               Unknown  Unknown
quick.MPI          000000000055D8A0  electdiis_                277  scf.f90
quick.MPI          0000000000555D03  scf_                       40  scf.f90
quick.MPI          00000000004200E0  getenergy_                 94  getEnergy.f90
quick.MPI          0000000000404F34  MAIN__                    210  main.f90
quick.MPI          0000000000404C9E  Unknown               Unknown  Unknown
libc-2.17.so       00007FEF0A8F8555  __libc_start_main     Unknown  Unknown
quick.MPI          0000000000404BA9  Unknown               Unknown  Unknown

Replacing it with DGEMM solves the problem.
